//Clear variables from watch window
expRemoveAll()
//AddWatchWindowVars lab 1
expAdd ("LLC_buildLevel",getNatural())
expAdd ("LLC_board_Status.enum_boardStatus",getNatural())
expAdd ("LLC_startFlag",getNatural())
expAdd ("LLC_vSec_Volts",getNatural())
expAdd ("LLC_iPriReso_Amps",getNatural())
expAdd ("LLC_iSec_Amps",getNatural())
expAdd ("LLC_periodRef_debug_pu",getNatural())
expAdd ("LLC_periodRef_pu",getNatural())
expAdd ("LLC_dutySet_debug_pu",getNatural())
expAdd ("LLC_dutySet_pu",getNatural())
expAdd ("EPwm1Regs.CMPA.CMPA",getNatural())
expAdd ("EPwm1Regs.CMPB.CMPB",getNatural())
expAdd ("EPwm1Regs.TBPRD",getNatural())
expAdd ("EPwm2Regs.CMPA.CMPA",getNatural())
expAdd ("EPwm2Regs.CMPB.CMPB",getNatural())
expAdd ("EPwm2Regs.TBPRD",getNatural())
expAdd ("EPwm1Regs.TZFLG",getNatural())
expAdd ("EPwm2Regs.TZFLG",getNatural())